# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicInfo',
            new_name='Basic',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
