# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_auto_20180821_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=b'mystatic/None/1.jpg', upload_to=b'mystatic/'),
        ),
    ]
