# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_auto_20180821_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_headline', models.CharField(default=b'Django project', max_length=200)),
                ('project_description', models.TextField(blank=True, max_length=300)),
                ('project_from', models.DateField(default=django.utils.timezone.now)),
                ('project_to', models.DateField(default=django.utils.timezone.now)),
                ('extra_info', models.TextField(default=b'salary 13.3 lpa', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
